name: Makefile CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Dependencies
      run: |
        ./install-deps-debian.sh  # Install dependencies with 'apt'
        make dependencies         # Download and extract the Binutils 2.39 and GCC 12.2.0 sources

    - name: Build binutils
      run: make build-binutils    # Build Binutils 2.39

    - name: Install binutils
      run: make install-binutils  # Install Binutils 2.39

    - name: Build GCC
      run: make build-gcc         # Build GCC 12.2.0

    - name: Install GCC
      run: make install-binutils  # Install GCC 12.2.0
